app/urls.py
from django.urls import path
from . import views
from .views import HomePageView, RecipesView, CreateRecipeView, RecipeDetailsView, UpdateRecipeView, DeleteRecipeView, \
    UserSaveRecipeView

urlpatterns = [
    path('', HomePageView.as_view(), name='home page'),
    path('recipes', RecipesView.as_view(), name='recipes'),
    path('recipe/create/', CreateRecipeView.as_view(), name='create recipe'),
    path('recipe/details/<int:pk>', RecipeDetailsView.as_view(), name='recipe details'),
    path('recipe/edit/<int:pk>/', UpdateRecipeView.as_view(), name='edit recipe'),
    path('recipe/delete/<int:pk>', DeleteRecipeView.as_view(), name='delete recipe'),
    path('save/<int:pk>', UserSaveRecipeView.as_view(), name='save recipe'),
]

python_web_framework_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
 #   path('recipe', include('app.urls')),
    path('account/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

from accounts.models import UserProfile


class Recipe(models.Model):
    title = models.CharField(max_length=250)
    image = models.ImageField(upload_to='recipes') #, blank=True, null=True ,'
    description = models.TextField()
    method = models.TextField()
    ingredients = models.CharField(max_length=250)
    time = models.IntegerField()

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id}; {self.title}; {self.user.user.username}'



class SaveRecipe(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    test = models.CharField(max_length=2)

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


class Comment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    text = models.TextField(blank=False)

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

templates/recipes/create_recipe.html
{% extends 'shared/base.html' %}
{% load bootstrap4 %}
{% block site_content %}

    <div class="container">
        <h1 class= 'text-center' style="font-size: 50px; padding-top: 25px; color: #fff">Add Recipe</h1>
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <form method="post" action="{% url 'create recipe' %}" class="furniture-form" enctype="multipart/form-data"
                                                                            style="color: #fff">
                    {% for field in form %}
                        {% bootstrap_field field %}
                    {% endfor %}
                    {% csrf_token %}
                    <button class="btn btn-outline-dark" type="submit" style="color: #fff; margin-top: 10px; margin-bottom: 20px">
                        Create Recipe</button>
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>

{% endblock %}

templates/recipes/delete_recipe.html
{% extends 'shared/base.html' %}
{% block site_content %}
    <div class="container">
        <div class="row">
        <div class="col-lg-12 text-center" style="color: #fff">
            <h1>Are you sure you want to delete your recipe {{ recipe.title }}?</h1>
            <div class="m-auto d-flex justify-content-center">
                 <div class="m-2">
                     <form method="post" action={% url 'delete recipe' recipe.pk %}>
                        {% csrf_token %}
                            <input type="submit" value="Confirm" class="btn btn-outline-dark" style="color: #fff">
                     </form>
                </div>
                <div class="m-2">
                    <a class="btn btn-outline-dark" style="color: #fff" href="javascript:history.back()">No, go back</a>
                </div>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

templates/recipes/edit_recipe.html
{% extends 'shared/base.html' %}
{% load bootstrap4 %}
{% block site_content %}

    <div class="container" style="color: #fff">
        <h1 class= 'text-center' style="font-size: 50px; padding-top: 25px;">Edit Recipe</h1>
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <form method="post" action="{% url 'edit recipe' recipe.pk %}" class="furniture-form" enctype="multipart/form-data">
                    {% for field in form %}
                        {% bootstrap_field field %}
                    {% endfor %}
                    {% csrf_token %}
                    <button class="btn btn-outline-dark" type="submit" style="color: #fff; margin-top: 10px; margin-bottom: 20px">
                        Edit</button>
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>

{% endblock %}

templates/recipes/recipe_details.html
{% extends 'shared/base.html' %}
{% block site_content %}



    <div class="text-center"  >
        <div class="text-center" >
            <h1 style="font-family: 'Berlin Sans FB', cursive; font-size: 500%; color: #fff">{{ recipe.title }}</h1>
        </div>


        <div class="d-inline p-3 w-50" style="font-family: 'JetBrains Mono', cursive; color: #fff">
            <div class="text-center" style="margin: 50px">
                <h5>{{ recipe.description }}</h5>
            </div>
        </div>


        <div class="text-center" style="padding: 20px">
            <img src="{{ recipe.image.url }}" alt="image of {{ recipe.name }}">

            <div class="text-center inline-deletelink w-auto" style="font-family: 'Bernard MT Condensed', cursive; color: #fff">
                <h6>Created by: {{ recipe.user.user.username }}</h6>
                <h6>Saved: {{ recipe.saverecipe_set.count }}</h6>

            {% if can_save %}
                {% if has_saved %}
                <a href="{% url 'save recipe' recipe.id %}"><svg style="color: #fff" width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-bookmark-star-fill" fill="black" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M4 0a2 2 0 0 0-2 2v13.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4zm4.16 4.1a.178.178 0 0 0-.32 0l-.634 1.285a.178.178 0 0 1-.134.098l-1.42.206a.178.178 0 0 0-.098.303L6.58 6.993c.042.041.061.1.051.158L6.39 8.565a.178.178 0 0 0 .258.187l1.27-.668a.178.178 0 0 1 .165 0l1.27.668a.178.178 0 0 0 .257-.187L9.368 7.15a.178.178 0 0 1 .05-.158l1.028-1.001a.178.178 0 0 0-.098-.303l-1.42-.206a.178.178 0 0 1-.134-.098L8.16 4.1z"></path>
</svg></a>
                {% else %}
                <a href="{% url 'save recipe' recipe.id %}"><svg style="color: #fff" width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-bookmark-star" fill="black" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"></path>
  <path d="M7.84 4.1a.178.178 0 0 1 .32 0l.634 1.285a.178.178 0 0 0 .134.098l1.42.206c.145.021.204.2.098.303L9.42 6.993a.178.178 0 0 0-.051.158l.242 1.414a.178.178 0 0 1-.258.187l-1.27-.668a.178.178 0 0 0-.165 0l-1.27.668a.178.178 0 0 1-.257-.187l.242-1.414a.178.178 0 0 0-.05-.158l-1.03-1.001a.178.178 0 0 1 .098-.303l1.42-.206a.178.178 0 0 0 .134-.098L7.84 4.1z"></path>
</svg></a>
                {% endif %}
            {% endif %}

            </div>
        </div>


    </div>

    <div style="font-family: 'Berlin Sans FB', cursive; padding: 5%; color: #fff">
        <h5>Ingredients:</h5>
        {% for ingredient in ingredients_list %}
            <li>{{ ingredient }}</li>
        {% endfor %}
    </div>

    <div  style="font-family: 'Berlin Sans FB', cursive; ; padding: 5%; color: #fff">
        <h5>Method:</h5>
        {% for method in methods %}
            <ul>{{ method }}</ul>
        {% endfor %}
    </div>



    <div class="d-block" style="background-color: -moz-nativehyperlinktext; padding:5%">
    
        <div class="box">
            <form method="post" action="{% url 'recipe details' recipe.id %}"style="color: #fff">
                {{ form }}
                {% csrf_token %}
                <button class="btn btn-outline-dark" type="submit" style="color: #fff; margin-top: 10px; margin-bottom: 10px">
                    Add comment</button>
            </form>
        </div>


        {% if recipe.comment_set.count > 0 %}
            {% for comment in recipe.comment_set.all %}
                <div class="box" style="font-family: Constantia ; color: #fff; padding-top: 15px">
                    <a style="color: #fff">{{ comment.user.user.username }} says:</a>
                    <h5><em>{{ comment.text }}</em></h5>
                </div>
            {% endfor %}
        {% else %}
        <div class="box" style="color: #fff">
            <h3>There are no comments for this recipe. </h3>
        </div>
        {% endif %}

    </div>

{% endblock %}

templates/recipes/recipes.html
{% extends 'shared/base.html' %}
{% block site_content %}

    <h1 class= 'text-center' style="font-size: 50px; padding-top: 25px; color: #fff">Festive Recipes</h1>
    <div class="row" style="padding: 100px; padding-block: 50px">
    {% for recipe in recipes %}
        <div class="row-3-col" style="margin: 25px">
            <div class="card" style="width: 18rem; padding: 15px; background: transparent; margin-left: 50%; margin-right: 50%;">
                <img src="{{ recipe.image.url }}" class="card-img-top" alt="{{ recipe.title }}"
                sizes="width="100px height="200px">
                <div class="card-body">
                    <h4 class="card-title" style="font-size: 30px; color: #fff">{{ recipe.title }}</h4>
                    <a href="{% url 'recipe details' recipe.id %}" class="btn btn-outline-dark" style="color: #fff;
                        font-family: cursive">See details</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>

{% endblock %}